name: webdm
vendor: Sergio Schvezov <sergio.schvezov@canonical.com>
icon: meta/clap.png
source: lp:webdm
version: 0.5
architecture: UNKNOWN_ARCH
services:
    - name: avahi
      start: metabin
      description: Avahi daemon
      security-policy:
          apparmor: meta/avahi.profile
          seccomp: meta/avahi.seccomp
