#!/bin/sh
set -e

platform=$(uname -i)

case $platform in
    x86_64)
        arch=amd64
        ;;
    armv7l)
        arch=armhf
        ;;
    *)
        echo "unknown platform for snappy-magic: $platform. remember to file a bug or better yet: fix it :)"
        ;;
esac

exec $SNAP_APP_PATH/bin/$arch/metabin

# never reach this
exit 1
